# Docker Compose configuration to watch for file changes in my local environment
# Author: Andrew Jarombek
# Date: 6/26/2019

version: '3.7'
services:
  watch:
    build:
      context: ../../infra/docker
      dockerfile: local.watch.dockerfile
    networks:
      - local-saints-xctf-api-net

networks:
  local-saints-xctf-api-net:
    driver: bridge