# Docker Compose configuration for the MySQL database in my local environment
# Author: Andrew Jarombek
# Date: 6/26/2019

version: '3.7'
services:
  db:
    build:
      context: ../../infra/docker
      dockerfile: local.db.dockerfile
    networks:
      - local-saints-xctf-api-net

networks:
  local-saints-xctf-api-net:
    driver: bridge