# Docker Compose configuration for the API using ECR images.  Simulates the setup of the application in production.
# Author: Andrew Jarombek
# Date: 9/25/2020

version: '3.7'
services:
  saints-xctf-api-flask:
    image: 739088120071.dkr.ecr.us-east-1.amazonaws.com/saints-xctf-api-flask:1.0.0
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - ENV=${ENV}
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_SHARED_CREDENTIALS_FILE=.aws/credentials
    networks:
      - saints-xctf-api-net
  saints-xctf-api-nginx:
    image: 739088120071.dkr.ecr.us-east-1.amazonaws.com/saints-xctf-api-nginx:1.0.0
    ports:
    - 80:80
    networks:
      - saints-xctf-api-net
    depends_on:
      - saints-xctf-api-flask

networks:
  saints-xctf-api-net:
    driver: bridge