# Docker Compose configuration for the API in my local environment
# Author: Andrew Jarombek
# Date: 6/22/2019

version: '3.7'
services:
  saints-xctf-api:
    domainname: saints-xctf-api
    build:
      context: ../../api/src/
      dockerfile: local.api.dockerfile
      # Needed to connect to the running MySQL database - https://stackoverflow.com/a/47068162
      network: host
    environment:
      - ENV=local
    ports:
      - 5000:5000
    networks:
      - local-saints-xctf-api-net

networks:
  local-saints-xctf-api-net:
    driver: bridge