# Docker Compose configuration for the API in my local environment
# Author: Andrew Jarombek
# Date: 6/22/2019

version: '3.7'
services:
  api:
    build:
      context: ../../api/src/
      dockerfile: local.api.dockerfile
      # Needed to connect to the running MySQL database - https://stackoverflow.com/a/47068162
      network: host
    networks:
      - local-saints-xctf-api-net
    volumes:
      - type: volume
        source: local-saints-xctf-api-vol
        target: /src

networks:
  local-saints-xctf-api-net:
    driver: bridge

volumes:
  local-saints-xctf-api-vol: