# Docker Compose configuration for the MySQL database in my local environment
# Author: Andrew Jarombek
# Date: 6/26/2019

version: '3.7'
services:
  db:
    build:
      context: ../../api/src/
      dockerfile: local.db.dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: saintsxctf
    ports:
      - 3306:3306
    networks:
      - local-saints-xctf-api-net

networks:
  local-saints-xctf-api-net:
    driver: bridge